### ISSUE TITLE
Rust Fails to Build

### ISSUE THREAD

**Issue by dslm4515** [dslm4515/BMLFS#6]
Hardware: Raspberry Pi 4 _4GB RAM_
Distro: MLFS-7.00
Arch: aarch64
Package: rustc-1.46.0
Bootstrap: Cargo 1.44.0 + rust 1.44.0 + rust-stdlib-1.44.0
Method: Both Void and Alpine

Rust fails to build .. on aarch64[, so far]:

```
   Compiling bootstrap v0.0.0 (/src-blfs/rustc-1.46.0-src/src/bootstrap)
error[E0658]: use of unstable library feature 'str_strip': newly added
   --> src/bootstrap/lib.rs:439:31
    |
439 |             .filter_map(|x| x.strip_prefix("release:"))
    |                               ^^^^^^^^^^^^
    |
    = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information
    = help: add `#![feature(str_strip)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'str_strip': newly added
    --> src/bootstrap/lib.rs:1092:22
     |
1092 |                 line.strip_prefix("version = \"").and_then(|s| s.strip_suffix("\""))
     |                      ^^^^^^^^^^^^
     |
     = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information
     = help: add `#![feature(str_strip)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'str_strip': newly added
    --> src/bootstrap/lib.rs:1092:66
     |
1092 |                 line.strip_prefix("version = \"").and_then(|s| s.strip_suffix("\""))
     |                                                                  ^^^^^^^^^^^^
     |
     = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information
     = help: add `#![feature(str_strip)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'str_strip': newly added
   --> src/bootstrap/compile.rs:968:22
    |
968 |                     .strip_prefix(&prefix[..])
    |                      ^^^^^^^^^^^^
    |
    = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information
    = help: add `#![feature(str_strip)]` to the crate attributes to enable

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `bootstrap`.

To learn more, run the command again with --verbose.
failed to run: /src-blfs/rustc-1.46.0-src/stage0/bin/cargo build --manifest-path /src-blfs/rustc-1.46.0-src/src/bootstrap/Cargo.toml --locked --frozen
Build completed unsuccessfully in 0:00:28
```

**Comment by dslm4515** [comment]
Cannot find any patches or hints to fix error.

Attempting to build `rustc-1.45.0` with Alpine-Linux built `cargo 1.44.0` + `rust 1.44.0` + `rust-stdlib-1.44.0`, using Alpine-Linux's build method.

**Comment by dslm4515** [comment]
Build competed with `rustc-1.45.1` using alpine build cargo 1.44.0 + rust 1.44.0 + rust-stdlib-1.44.0 installed in `rustc-1.45.1/stage0`... had to use libressl-3.0.0 as rustc 1.45.1 will not build with anything newer than libressl-3.0.x.   Used Alpine Linux's method and patches.

Perhaps, rustc-1.46.0 needs rustc-1.45.x to build?
